//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPeicefinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RateID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Rate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual MainOrder MainOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
